version: "3.8"

services:
  
      
  restaurant_api:
    build: .
    container_name: restaurant
    ports:
      - "80:8000"
    environment:
      DATABASE_NAME: db_postgres
      DATABASE_USER: user_postgres
      DATABASE_PASSWORD: password_postgres
      DATABASE_HOST: postgres_db
      DATABASE_PORT: 5432
      EMAIL_HOST_PASSWORD: "hbyc ljcj mjwh fpgz"
      EMAIL_HOST: smtp.gmail.com
      EMAIL_HOST_USER: rahulpoppad.1999@gmail.com
      EMAIL_USE_TLS: 1
      EMAIL_PORT: 587
      AWS_ACCESS_KEY_ID: 'ASIATUYJP7SUL7QXC62E'
      AWS_SECRET_ACCESS_KEY: 'nQA3xSno4uXCEE25yKM55e+KxuBRQU3SsUMirX7x'
      DEBUG: 1

    networks:
      - restaurant_network

networks:
  restaurant_network: {}